name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages for python
      run: |
       name:
     
         - python3-pip
         - python3-dev
         - build-essential
         - libssl-dev
         - libffi-dev
         - python3-setuptools
         - python3-venv
       update_cache: yes
      
    
      
   
